
services:
  
#  ui-service:
#    image: shop-ui-service
#    build:
#      context: ./Shop
#      dockerfile: Dockerfile
#    pull_policy: build
#    ports: 
#      - "8105:8105"    
#    healthcheck:
#      test: "curl -f http://localhost:8105/"
#      interval: 5s
#      timeout: 5s
#      retries: 5
#    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: P@ssw0rd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_PROXY: edge
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shop-network
      - shop-pg-network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 60s
    restart: unless-stopped

  auth-service:
    image: shop-auth-service
    build:
      context: .
      dockerfile: AuthorizationService/AuthorizationService/Dockerfile
    container_name: auth-service
    pull_policy: build
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Keycloak__Realm: number1shop
      Keycloak__AuthServerUrl: http://keycloak:8080/
      Keycloak__SslRequired: none
      Keycloak__Resource: auth-service
      Keycloak__VerifyTokenAudience: true
      Keycloak__Credentials__Secret: your-auth-service-secret
    ports:
      - "5004:8080"
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - shop-network
    restart: unless-stopped


  users-service:
    image: shop-users-service
    build:
      context: .
      dockerfile: UsersService/UsersService/Dockerfile
    pull_policy: build
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: Host=postgres:5432;Username=postgres;Password=P@ssw0rd;Database=UsersDb
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shop-network
      - shop-pg-network
  
  cart-service:
    image: shop-cart-service
    build:
      context: .
      dockerfile: CartService/CartService/Dockerfile
    pull_policy: build
    environment:
      CONNECTION_STRING: Host=postgres:5432;Username=postgres;Password=P@ssw0rd;Database=CartDb
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_USER: guest
      RMQ_PASSWORD: guest
      RMQ_CART_PRODUCT_QUEUE: cart-product-messages-queue
      RMQ_PRODUCT_EXCHANGE: product-messages-exchange
      
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 5s
      timeout: 5s
      retries: 5
    
    restart: unless-stopped
    
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - shop-network
      - shop-pg-network
  
  favorite-service:
    image: shop-favorite-service
    build:
      context: .
      dockerfile: FavoriteService/FavoriteService/Dockerfile
    pull_policy: build
    environment:
      CONNECTION_STRING: Host=postgres:5432;Username=postgres;Password=P@ssw0rd;Database=FavoriteDb

    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - shop-network
      - shop-pg-network
  
  catalog-service:
    image: shop-catalog-service
    build:
      context: .
      dockerfile: CatalogService/CatalogService/Dockerfile
    pull_policy: build
    environment:
      CONNECTION_STRING: Host=postgres:5432;Username=postgres;Password=P@ssw0rd;Database=CatalogDb
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_USER: guest
      RMQ_PASSWORD: guest
      RMQ_PRODUCT_FROM_CATALOG_QUEUE: catalog-product-messages-queue

    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - shop-network
      - shop-pg-network

  orders-service:
    image: shop-orders-service
    build:
      context: .
      dockerfile: OrdersService/OrdersService/Dockerfile
    pull_policy: build
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: Host=postgres:5432;Username=postgres;Password=P@ssw0rd;Database=Orders
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shop-network
      - shop-pg-network

  storage-service:
    image: shop-storage-service
    build:
      context: .
      dockerfile: StorageService/StorageService/Dockerfile
    pull_policy: build
    environment:
      CONNECTION_STRING: Host=postgres:5432;Username=postgres;Password=P@ssw0rd;Database=StorageDb
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_USER: guest
      RMQ_PASSWORD: guest
      RMQ_CART_PRODUCT_QUEUE: storage-product-messages-queue
      RMQ_PRODUCT_EXCHANGE: storage-messages-exchange

    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - shop-network
      - shop-pg-network
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_MULTIPLE_DATABASES: UsersDb,CartDb,FavoriteDb,CatalogDb,Orders,StorageDb
    ports:
      - "5432:5432"
    networks:
      - shop-pg-network
    labels:
      - app=shop
      
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 5s
      retries: 5
      
      
  rabbitmq:
    image: rabbitmq:4.1-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    
    restart: unless-stopped
    
    networks:
      - shop-network
    labels:
      - app=shop
    healthcheck:
      test: "rabbitmqctl status > /dev/null 2>&1;"
      interval: 5s
      timeout: 5s
      retries: 5
 
  nginx-proxy:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./ApiGate/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./ApiGate:/etc/nginx/ApiGate:ro
    
    depends_on:
      users-service:
        condition: service_healthy
      cart-service:
        condition: service_healthy
      favorite-service:
        condition: service_healthy
      orders-service:
        condition: service_healthy
      #ui-service:
      #  condition: service_healthy
        
    restart: unless-stopped

    networks:
      - shop-network
    labels:
      - app=shop

    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  shop-network:
    name: shop-network
    labels:
      - app=shop
  shop-pg-network:
    name: shop-pg-network
    labels:
      - app=shop
