// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.FavoriteService.Model;

#nullable disable

namespace Shop.FavoriteService.Migrations
{
    [DbContext(typeof(EfContext))]
    partial class EfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Shop.FavoriteService.Model.FavoriteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FavoriteListId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteListId");

                    b.ToTable("FavoriteItem");
                });

            modelBuilder.Entity("Shop.FavoriteService.Model.FavoriteList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FavoriteList");
                });

            modelBuilder.Entity("Shop.FavoriteService.Model.FavoriteItem", b =>
                {
                    b.HasOne("Shop.FavoriteService.Model.FavoriteList", null)
                        .WithMany("Items")
                        .HasForeignKey("FavoriteListId");
                });

            modelBuilder.Entity("Shop.FavoriteService.Model.FavoriteList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
